parameters:
    pim_excel_connector.archiver.file_iterator_reader_archiver.class: Pim\Bundle\ExcelConnectorBundle\Archiver\FileIteratorReaderArchiver

services:
    pim_excel_connector.archiver.file_iterator_reader_archiver:
        class: %pim_excel_connector.archiver.file_iterator_reader_archiver.class%
        arguments:
            - '@pim_archivist_filesystem'
        tags:
            - { name: pim_base_connector.archiver }