connector:
    name: Akeneo Excel Connector
    jobs:
        excel_product_export:
            title: pim_excel_connector.jobs.xlsx.product.export.title
            type: export
            steps:
                export:
                    title: pim_excel_connector.jobs.product.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_excel_connector.processor.normalizer.product_csv
                        writer:    pim_base_connector.writer.xlsx.product

        excel_product_family_export:
            title: pim_excel_connector.jobs.xlsx.product_family.export.title
            type: export
            steps:
                export:
                    title: pim_excel_connector.jobs.product.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_excel_connector.processor.normalizer.product_csv
                        writer:    pim_base_connector.writer.xlsx.product_family

        excel_2003_xml_product_export:
            title: pim_excel_connector.jobs.excel_2003_xml.product.export.title
            type: export
            steps:
                export:
                    title: pim_excel_connector.jobs.product.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_excel_connector.processor.normalizer.product_csv
                        writer:    pim_excel_connector.writer.excel_2003_xml

        excel_product_import:
            title: pim_excel_connector.jobs.xlsx.product.import.title
            type:  import
            steps:
                import:
                    title:     pim_excel_connector.jobs.product.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls.product
                        processor: pim_base_connector.processor.product
                        writer:    pim_base_connector.writer.doctrine.product
                import_associations:
                    title:     pim_base_connector.jobs.csv_product_import.import_associations.title
                    services:
                        reader:    pim_base_connector.reader.cached_association
                        processor: pim_base_connector.processor.association
                        writer:    pim_base_connector.writer.doctrine.association

        excel_init_import:
            title: pim_excel_connector.jobs.init_import.import.title
            type: import
            steps:
                attribute_groups:
                    title: pim_excel_connector.jobs.attribute_group.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.attribute_group
                        processor: pim_base_connector.processor.attribute_group
                        writer:    pim_excel_connector.writer.doctrine.attribute_group
                group_types:
                    title: pim_excel_connector.jobs.group_type.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.group_type
                        processor: pim_base_connector.processor.group_type
                        writer:    pim_excel_connector.writer.doctrine.group_type
                association_types:
                    title: pim_excel_connector.jobs.association_type.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.association_type
                        processor: pim_base_connector.processor.association_type
                        writer:    pim_base_connector.writer.doctrine.association_type
                categories:
                    title: pim_excel_connector.jobs.category.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.category
                        processor: pim_base_connector.processor.category
                        writer:    pim_base_connector.writer.doctrine.category
                channels:
                    title: pim_excel_connector.jobs.channel.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.channel
                        processor: pim_base_connector.processor.channel
                        writer:    pim_excel_connector.writer.doctrine.channel
                attributes:
                    title: pim_excel_connector.jobs.attribute.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.attribute
                        processor: pim_base_connector.processor.attribute
                        writer:    pim_base_connector.writer.doctrine.attribute
                attribute_options:
                    title: pim_excel_connector.jobs.attribute_option.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.attribute_option
                        processor: pim_base_connector.processor.attribute_option
                        writer:    pim_base_connector.writer.doctrine.attribute_option
                families:
                    title: pim_excel_connector.jobs.family.import.title
                    services:
                        reader:    pim_excel_connector.reader.xls_init.family
                        processor: pim_base_connector.processor.family
                        writer:    pim_excel_connector.writer.doctrine.family
