parameters:
    pim_excel_connector.reader.xls_init.class: Pim\Bundle\ExcelConnectorBundle\Reader\XlsxFileReader

services:
    pim_excel_connector.reader.xls_init:
        class: %pim_excel_connector.reader.xls_init.class%
        abstract: true
        arguments:
            - '@pim_excel_connector.iterator.file.factory'

    pim_excel_connector.reader.xls_init.attribute_group:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^attribute_groups/' ]

    pim_excel_connector.reader.xls_init.channel:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^channels/' ]

    pim_excel_connector.reader.xls_init.category:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^categories/' ]
            - true

    pim_excel_connector.reader.xls_init.option:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^options/' ]

    pim_excel_connector.reader.xls_init.group_type:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^group_types/' ]

    pim_excel_connector.reader.xls_init.association_type:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^association_types/' ]

    pim_excel_connector.reader.xls_init.attribute:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.attribute.class%
            - label_row: 6
              data_row: 7
              skip_empty: true
              include_worksheets: [ '/^family/', '/^attributes/' ]

    pim_excel_connector.reader.xls_init.attribute_option:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.class%
            - label_row: 3
              data_row: 4
              include_worksheets: [ '/^options/' ]

    pim_excel_connector.reader.xls_init.family:
        parent: pim_excel_connector.reader.xls_init
        arguments:
            - %pim_excel_connector.iterator.file.xlsx.family.class%
            - channel_label_row:   5
              attribute_label_row: 6
              attribute_data_row: 7
              code_row:    2
              code_column: 1
              labels_label_row: 1
              labels_data_row: 2
              labels_column: 4
              include_worksheets: [ '/^family/' ]

    pim_excel_connector.reader.xls.product:
        parent: pim_excel_connector.reader.xls_init
        arguments:
          - %pim_excel_connector.iterator.file.xlsx.class%
